=== DMathelier/INU3011_TP/DTD/miroir.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Modèle XML développé dans le cadre du cours INU3011 Documents structurés -->
<!-- EBSI - Université de Montréal -->

<!-- Équipe: Céline Hostiou (20096330), Daphné Mathelier (20177495). -->
<!-- Élément de plus haut niveau: miroir -->

<!--
Les commentaires commençant par "doc:" sont utilisés par oXygen comme documentation d’aide à la
saisie. Ils sont affichés en infobulles pendant l’édition de documents conformes à la DTD lorsque le
curseur survole un nom d’élément ou d’attribut.
-->

<!-- doc: Description d’un miroir -->
<!ELEMENT miroir (suiviModif, aspect, mesures, origine, valeur?, usage?) >

<!-- doc: Identifiant de la fiche qui correspond au numéro attribué au miroir (déterminé par la date d’acquisition). L’identifiant attribué à chaque miroir permet de nommer à la fois la fiche XML et l’image associée (s’il y en a une) Exemples:
  miroir1
  miroir22 -->
<!ATTLIST miroir ID NMTOKEN #REQUIRED>

<!-- doc: Attribut à n’utiliser que si une photo est associée à la fiche (indiquer "oui"). S’il n’y a pas de photo associée, ne pas utiliser cet attribut. -->
<!ATTLIST miroir photo (oui) #IMPLIED>

<!-- doc: Suivi des modifications apportées à la présente fiche -->
<!ELEMENT suiviModif (création, modification?)>

<!-- doc: Information sur la création de la fiche (obligatoire) -->
<!ELEMENT création (contributeur)>

<!-- doc: Date de création de la fiche au format AAA-MM-JJ Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST création date NMTOKEN #REQUIRED>

<!-- doc: Informations sur la dernière modification de la fiche -->
<!ELEMENT modification (contributeur)>

<!-- doc: Date de dernière modification de la fiche au format AAA-MM-JJ Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST modification date NMTOKEN #REQUIRED>

<!-- doc: Personne ayant créé ou modifié la fiche au format "Prénom Nom" (un seul contributeur par élément) Exemples:
  Daphné Mathelier
  Céline Hostiou -->
<!ELEMENT contributeur (#PCDATA)>

<!-- doc: Informations relatives à l’aspect du miroir. Il est obligatoire de renseigner la forme et la couleur du miroir selon des listes prédéfinies, ainsi que son style (au minimum son époque). D’autres renseignements sont facultatifs comme la présence d’un cadre ou l’orientation du miroir -->
<!ELEMENT aspect (style, cadre?)>

<!-- doc: Couleur principale du miroir. S’il y a plusieurs couleurs dominantes, choisir la valeur d’attribut "multicolore" -->
<!ATTLIST aspect couleur (argent | beige | blanc | bleu | brun | cuivre | gris | jaune | multicolore | noir | or | orange | rose | rouge | transparent | vert | violet) #REQUIRED>

<!-- doc: Forme du miroir. Si celle-ci est difficile à décrire, choisir la valeur d’attribut "irrégulier" -->
<!ATTLIST aspect forme (arabesque | carré | hexagone  | irrégulier  | octogone | ovale | rectangle | rond | triangle) #REQUIRED>

<!-- doc: Précisions sur le style si celui-ci est très marqué Exemples:
  Industriel
  Joli miroir <em>vintage</em> -->
<!ELEMENT style (#PCDATA | em | sup)*>

<!-- doc: Époque du miroir (précision obligatoire) Exemples:
  Contemporain
  XVIIIᵉ siècle -->
<!ATTLIST style époque CDATA #REQUIRED>

<!-- doc: Description du cadre (élément facultatif à n’utiliser que s’il y a un cadre à décrire) Exemples:
  Cadre en métal d’une épaisseur de 5 cm
  Discret cadre en faux bois -->
<!ELEMENT cadre (#PCDATA | em | sup)*>

<!-- doc: Mesures du miroir (il est obligatoire de mentionner au minimum la hauteur et la largeur du miroir) -->
<!ELEMENT mesures (hauteur, largeur, profondeur?, poids?)>

<!-- doc: Hauteur du miroir en cm Exemples:
  200
  50 -->
<!ELEMENT hauteur (#PCDATA)>

<!-- doc: Largeur du miroir en cm Exemples:
  90
  150,5 -->
<!ELEMENT largeur (#PCDATA)>

<!-- doc: Profondeur du miroir en cm (à compléter si pertinent) Exemples:
  5
  0,25 -->
<!ELEMENT profondeur (#PCDATA)>

<!-- doc: Poids du miroir en kg (à compléter si pertinent) Exemples:
  52,9
  0,25 -->
<!ELEMENT poids (#PCDATA)>

<!-- doc: Informations sur l’origine du miroir. Il est obligatoire de préciser comment le collectionneur a obtenu le miroir. En fonction de cette réponse, d’autres informations pourront être renseignées comme le prix d’achat  -->
<!ELEMENT origine (commentaire?)>

<!-- doc: Date d’acquisition du miroir au format AAAA-MM-JJ. Élément obligatoire permettant d’attribuer les identifiants des miroirs (numérotation chronologique) Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST origine dateAcquisition NMTOKEN #REQUIRED>

<!-- doc: Contexte d'acquisition du miroir. Trois possibilités : achat, don ou indéterminé -->
<!ATTLIST origine moyenAcquisition (achat | don | indéterminé) #REQUIRED>

<!-- doc: Prix d'achat du miroir (à compléter si le miroir a été acheté et que cette information est connue) Exemples:
  50
  499 -->
<!ATTLIST origine prixAchatEuros CDATA #IMPLIED>

<!-- doc: Informations supplémentaires sur le miroir (par exemple sur son créateur ou sur le mouvement artistique dont il est issu). Texte libre qui peut comprendre plusieurs paragraphes, de l’emphase, des exposants et des liens, en fonction de la quantité d’informations que souhaite ajouter le collectionneur Exemples:
  Miroir très rare de fabrication italienne dont on ne trouve plus que dix exemplaires dans le monde
  <para> Ce miroir a été commercialisé en 2020 par l'enseigne <lienExterne URL="http://www.maisonsdumonde.com">Maison du monde</lienExterne></para> -->
<!ELEMENT commentaire (para+)>

<!-- doc: Valeur estimée du miroir (information facultative car évolutive et difficile à estimer) Exemples:
  100 €
  En février 2021, le prix du miroir était estimé à 715 € -->
<!ELEMENT valeur (#PCDATA)>

<!-- doc: Informations sur l’usage attendu du miroir. Texte libre qui peut comprendre plusieurs paragraphes, de l'emphase, des exposants et des liens, en fonction de la quantité d'informations que souhaite ajouter le collectionneur Exemples:
  Ce miroir de poche est très léger et peut se glisser facilement dans une valise
  Grand miroir d'entrée permettant de visualiser un corps en entier -->
<!ELEMENT usage (para+)>

<!-- doc: Bloc de paragraphe pouvant contenir des sous-éléments en emphase, en exposant et des liens (internes ou externes). Exemples:
  Un miroir très <em>british</em> !
  Dans le même style, voir également <lien ID="miroir22">ce miroir</lien>. -->
<!ELEMENT para (#PCDATA | em | sup | lienInterne | lienExterne)*>

<!-- doc: Passage en emphase. Exemples:
  style <em>british</em> et romantique
  miroir <em>so chic</em> -->
<!ELEMENT em (#PCDATA)>

<!-- doc: Passage en exposant. Exemples:
  XX<sup>e</sup> siècle
  sa 1<sup>re</sup> utilisation -->
<!ELEMENT sup (#PCDATA)>

<!-- doc: Lien pour renvoyer à un autre miroir de la collection dans un paragraphe de texte via son identifiant (attribut ID) Exemples:
  numéro 1
  ce miroir -->
<!ELEMENT lienInterne (#PCDATA)>

<!-- doc: Identifiant (ID) du miroir auquel le lien renvoie. Exemples:
  miroir1
  miroir22 -->
<!ATTLIST lienInterne ID NMTOKEN #REQUIRED>

<!-- doc: Lien pour renvoyer à une ressource externe via une URL Exemples:
  Bouclair
  Proantic.com -->
<!ELEMENT lienExterne (#PCDATA)>

<!-- doc: Ressource externe (URL) à laquelle le lien renvoie. Exemples:
  http://www.bouclair.com/fr/decor-mural/miroirs/
  http://www.proantic.com/miroir.php -->
<!ATTLIST lienExterne URL CDATA #REQUIRED>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir45.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir45" photo="oui">
    <suiviModif>
        <creation date="2021-02-06">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-03-09">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="vert" forme="ovale">
        <style epoque="XXe siècle">Ce miroir moderne et coloré est créé et signé par l'artiste
            américain David Marshall. Conçu dans les années 1990, il est fait entièrement de verre
            sculpté. </style>
        <cadre>Un héron vert d'eau orne son pourtour.</cadre>
    </aspect>
    <mesures>
        <hauteur>99</hauteur>
        <largeur>71</largeur>
        <profondeur>3</profondeur>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="3500">
        <dateAcquisition>2020-09-17</dateAcquisition>
        <commentaire>
            <para>Ce miroir a été acquis auprès de la galerie Majdeltier, située dans le
                nord de la France, à Tourcoing, tout comme le <lienInterne ID="miroir38">miroir
                    38</lienInterne> de la collection. Le donataire comptait parmi ses habitués. Son
                catalogue d'oeuvres d'art du XXe siècle, son domaine de spécialité, est consultable
                sous ce <lienExterne URL="https://www.proantic.com/galerie/majdeltier/"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En septembre 2020, le prix du miroir était de 3500 €.</valeur>
    <usage>Ce miroir est voué à prendre appui sur un buffet, une commode, dans un salon, une salle à manger.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir17" photo="oui">
    <suiviModif>
        <creation date="2021-02-08">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-02-09">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="or" forme="rond">
        <style epoque="contemporain">Ce miroir appelé "Capsule" se décompose en deux parties: un petit cercle
            surmontant un plus grand. Ceux-ci sont unis par une fine tige ovoïde.</style>
        <cadre>Le cadre est en métal doré.</cadre>
    </aspect>
    <mesures>
        <hauteur>66</hauteur>
        <largeur>41</largeur>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="92">
        <dateAcquisition>2020-04-01</dateAcquisition>
        <commentaire>
            <para>Ce miroir circulaire, comme le <lienInterne ID="miroir22">miroir
                22</lienInterne>, a été acheté dans l'enseigne de décoration québécoise Zone. Il est
                visible sous ce <lienExterne
                    URL="https://www.zonemaison.com/fr/products/deco/miroirs/capsule/23754/miroir-double-or"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 92 dollars.</valeur>
    <usage>Ce miroir aurait avantage à être placé dans une pièce lumineuse, pour l'éclat de son cadre doré.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir9" photo="oui">
    <suiviModif>
        <creation date="2021-01-15">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-01-16">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="transparent" forme="rond">
        <style epoque="vintage">Ce miroir circulaire est agrémenté de trois rangées de perles de verre scintillantes.</style>
        <cadre>Des bijoux ornent le pourtour.</cadre>
    </aspect>
    <mesures>
        <hauteur>30</hauteur>
        <largeur>30</largeur>
        <profondeur>4,45</profondeur>
        <poids>6,35</poids>
    </mesures>
    <origine moyenAcquisition="don" prixAchat="99">
        <dateAcquisition>2020-03-31</dateAcquisition>
        <commentaire>
            <para>Ce miroir vintage, comme le <lienInterne ID="miroir17">miroir
                17</lienInterne>, a été conçu par The Tangerine Mirror Company. Sa fiche produit se trouve sous ce <lienExterne
                    URL="https://www.homedepot.ca/produit/the-tangerine-mirror-company-bijou-miroir-rond/1001384871"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 99 dollars.</valeur>
    <usage>Mieux vaut fixer ce miroir dans une pièce très claire afin de rehausser l'éclat des perles de verre qui y sont serties.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir38.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/Documents/GitHub/INU3011_TP/DTD/miroir.dtd">
<miroir ID="miroir38" photo="oui">
    <suiviModif>
        <création date="2021-03-01">
            <contributeur>Céline Hostiou</contributeur>
        </création>
        <modification date="2021-04-09">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="transparent" forme="triangle">
        <style époque="XXe siècle">
            <para>Ce miroir triangulaire est de style Art Déco. Il présente une
            belle mise en abyme avec son petit miroir intégré au tain mercurisé de couleur
            bronze.</para>
        </style>
        <cadre>
            <para>Il est encadré d'un sillon qui crée un mince contour biseauté.</para>
        </cadre>
    </aspect>
    <mesures>
        <hauteur>76</hauteur>
        <largeur>59</largeur>
        <profondeur>1</profondeur>
    </mesures>
    <origine dateAcquisition="2019-04-07" moyenAcquisition="achat" prixAchatEuros="290">
        <commentaire>
            <para>Ce miroir a été acquis auprès de la galerie Majdeltier, située dans le nord de la
                France, à Tourcoing, tout comme le <lienInterne ID="miroir45">miroir
                    45</lienInterne> de la collection. Le donataire comptait parmi ses habitués. Son
                catalogue d'oeuvres d'art du XXe siècle, son domaine de spécialité, est consultable
                sous ce <lienExterne URL="https://www.proantic.com/galerie/majdeltier/"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En juin 2020, le prix du miroir était de 290 €.</valeur>
    <usage>
        <para>Ce miroir est voué à être fixé à un mur, sans meuble dessous, pour bien mettre en valeur
            sa forme triangulaire tombante.</para>
    </usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/Documents/GitHub/INU3011_TP/DTD/miroir.dtd">
<?xml-stylesheet type="text/xsl" href="file:/Users/Daphne/Documents/GitHub/INU3011_TP/XSLT/HTML.xsl"?>

<miroir ID="miroir9" photo="oui">
    <suiviModif>
        <création date="2021-01-15">
            <contributeur>Céline Hostiou</contributeur>
        </création>
        <modification date="2021-02-16">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="transparent" forme="rond">
        <style époque="vintage">
            <para>ce miroir circulaire est agrémenté de trois rangées de perles de verre scintillantes.</para>
        </style>
        <cadre>
            <para>des bijoux ornent le pourtour.</para>
        </cadre>
    </aspect>
    <mesures>
        <hauteur>30</hauteur>
        <largeur>30</largeur>
        <profondeur>4,45</profondeur>
        <poids>6,35</poids>
    </mesures>
    <origine dateAcquisition="2017-02-13" moyenAcquisition="don">
        <commentaire>
            <para>Ce miroir vintage, comme le <lienInterne ID="miroir17">miroir
                17</lienInterne>, a été conçu par The Tangerine Mirror Company. Voir sa fiche produit chez <lienExterne
                    URL="https://www.homedepot.ca/produit/the-tangerine-mirror-company-bijou-miroir-rond/1001384871"
                    >Home Depot</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 99 $CAN (66 €).</valeur>
    <usage>
        <para>Mieux vaut fixer ce miroir dans une pièce très claire afin de rehausser l’éclat des perles de verre qui y sont serties.</para>
    </usage>
</miroir>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir12" photo="oui">
    <suiviModif>
        <creation date="2021-01-22">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-01-23">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="or" forme="octogone">
        <style epoque="vintage">Ce miroir dit "Makita", de la marque AMPM, est décoré de deux carrés en laiton superposés.</style>
        <cadre>Le cadre en métal a fait l'objet d'une finition en laiton vieilli.</cadre>
    </aspect>
    <mesures>
        <hauteur>70</hauteur>
        <largeur>70</largeur>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="259">
        <dateAcquisition>2020-03-31</dateAcquisition>
        <commentaire>
            <para>Ce miroir vintage, comme le <lienInterne ID="miroir22">miroir
                22</lienInterne>, est proposé par les Galeries Lafayette. Sa fiche produit se trouve sous ce <lienExterne
                    URL="https://www.galerieslafayette.com/p/miroir+metal+finition+vieillie+makita-ampm/300407151727/347"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 259 euros.</valeur>
    <usage>Ce miroir peut être indifféremment posé sur une commode, un meuble ou fixé au mur.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir42.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/ownCloud/4_DESS/Trimestre2/INU3011_Docs-structures/EVAL/TP3/Modele/miroir.dtd">
<miroir ID="miroir42" photo="oui">
    <suiviModif>
        <creation date="2021-02-24">
            <contributeur>Daphné Mathelier</contributeur>
        </creation>
        <modification date="2021-03-09">
            <contributeur>Céline Hostiou</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="blanc" forme="rectangle">
        <style epoque="XIXe siècle">Ce miroir rectangulaire comporte un trumeau imitant les
            pratiques de décoration qui ont eu cours à partir du règne de Louis XVI et se sont
            poursuivies au XIXe siècle. La pièce imitant le bois sculpté est soulignée d'une
            ornementation florale en cuivre.</style>
        <cadre>Le miroir est entouré d'un cadre en résine fabriqué à la commande dans un atelier
            d'artisan en France.</cadre>
    </aspect>
    <mesures>
        <hauteur>176</hauteur>
        <largeur>97</largeur>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="715 €">
        <dateAcquisition>2019-07-20</dateAcquisition>
        <commentaire>
            <para>Ce miroir a été acquis initialement par le collectionneur dans un magasin de la
                chaîne française <lienExterne URL="http://www.maisonsdumonde.com/">Maisons du
                    monde</lienExterne>. La description du miroir est consultable <lienExterne
                    URL="http://www.maisonsdumonde.com/FR/fr/p/miroir-trumeau-en-resine-ivoire-70x150-M21017760.htm"
                    >sous ce lien</lienExterne>.</para>
            <para>En ceci qu'il est rectangulaire et orné, il ressemble au <lienInterne
                    ID="miroir29">miroir 29</lienInterne> de la collection.</para>
        </commentaire>
    </origine>
    <valeur>En février 2021, le prix du miroir était estimé à 715 €</valeur>
    <usage>Ce miroir à fixer convient particulièrement à un salon, ou bien à une chambre, une entrée
        pour la vérification de l'habillement de pied en cap. Selon le vendeur, il est <em>idéal pour un salon ou même un dressing</em>
    </usage>
</miroir>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir22.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir22" photo="oui">
    <suiviModif>
        <creation date="2021-02-13">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-02-15">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="argent" forme="rond">
        <style epoque="vintage">Ce miroir rond date des années 1960. Il a pour matériaux le verre et
            le cristal.</style>
        <cadre>Le cadre est gravé et biseauté.</cadre>
    </aspect>
    <mesures>
        <hauteur>62</hauteur>
        <largeur>62</largeur>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="250">
        <dateAcquisition>2020-04-15</dateAcquisition>
        <commentaire>
            <para>Ce miroir circulaire, comme le <lienInterne ID="miroir50">miroir 50</lienInterne>,
                a été acquis auprès d'un brocanteur de Saint-Ouen, situé près de Paris. Bien que
                d'occasion, il ne présente ni fêlés ni impacts. Il est visible sous ce <lienExterne
                    URL="https://www.selency.fr/produit/55V2Q3Y2/miroir-rond-grave-et-biseaute-annees-60.html"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 250 euros.</valeur>
    <usage>Ce miroir peut être fixé dans n'importe quelle pièce du logement, dans un vestibule, un
        couloir.</usage>
</miroir>
