=== DMathelier/INU3011_TP/DTD/miroir.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Modèle XML développé dans le cadre du cours INU3011 Documents structurés -->
<!-- EBSI - Université de Montréal -->

<!-- Équipe: Céline Hostiou (20096330), Daphné Mathelier (20177495). -->
<!-- Élément de plus haut niveau: miroir -->

<!--
Les commentaires commençant par "doc:" sont utilisés par oXygen comme documentation d’aide à la
saisie. Ils sont affichés en infobulles pendant l’édition de documents conformes à la DTD lorsque le
curseur survole un nom d’élément ou d’attribut.
-->

<!-- doc: Description d’un miroir -->
<!ELEMENT miroir (suiviModif, aspect, mesures, origine, valeur?, usage?) >

<!-- doc: Identifiant de la fiche qui correspond au numéro attribué au miroir (déterminé par la date d’acquisition). L’identifiant attribué à chaque miroir permet de nommer à la fois la fiche XML et l’image associée (s’il y en a une) Exemples:
  miroir1
  miroir22 -->
<!ATTLIST miroir ID NMTOKEN #REQUIRED>

<!-- doc: Attribut à n’utiliser que si une photo est associée à la fiche (indiquer "oui"). S’il n’y a pas de photo associée, ne pas utiliser cet attribut. -->
<!ATTLIST miroir photo (oui) #IMPLIED>

<!-- doc: Suivi des modifications apportées à la présente fiche -->
<!ELEMENT suiviModif (création, modification?)>

<!-- doc: Information sur la création de la fiche (obligatoire) -->
<!ELEMENT création (contributeur)>

<!-- doc: Date de création de la fiche au format AAA-MM-JJ Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST création date NMTOKEN #REQUIRED>

<!-- doc: Informations sur la dernière modification de la fiche -->
<!ELEMENT modification (contributeur)>

<!-- doc: Date de dernière modification de la fiche au format AAA-MM-JJ Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST modification date NMTOKEN #REQUIRED>

<!-- doc: Personne ayant créé ou modifié la fiche au format "Prénom Nom" (un seul contributeur par élément) Exemples:
  Daphné Mathelier
  Céline Hostiou -->
<!ELEMENT contributeur (#PCDATA)>

<!-- doc: Informations relatives à l’aspect du miroir. Il est obligatoire de renseigner la forme et la couleur du miroir selon des listes prédéfinies, ainsi que son style (au minimum son époque). D’autres renseignements sont facultatifs comme la présence d’un cadre ou l’orientation du miroir -->
<!ELEMENT aspect (style, cadre?)>

<!-- doc: Couleur principale du miroir. S’il y a plusieurs couleurs dominantes, choisir la valeur d’attribut "multicolore" -->
<!ATTLIST aspect couleur (argent | beige | blanc | bleu | brun | cuivre | gris | jaune | multicolore | noir | or | orange | rose | rouge | transparent | vert | violet) #REQUIRED>

<!-- doc: Forme du miroir. Si celle-ci est difficile à décrire, choisir la valeur d’attribut "irrégulier" -->
<!ATTLIST aspect forme (arabesque | carré | hexagone  | irrégulier  | octogone | ovale | rectangle | rond | triangle) #REQUIRED>

<!-- doc: Précisions sur le style si celui-ci est très marqué Exemples:
  Industriel
  Joli miroir <em>vintage</em> -->
<!ELEMENT style (#PCDATA | em | sup)*>

<!-- doc: Époque du miroir (précision obligatoire) Exemples:
  Contemporain
  XVIIIᵉ siècle -->
<!ATTLIST style époque CDATA #REQUIRED>

<!-- doc: Description du cadre (élément facultatif à n’utiliser que s’il y a un cadre à décrire) Exemples:
  Cadre en métal d’une épaisseur de 5 cm
  Discret cadre en faux bois -->
<!ELEMENT cadre (#PCDATA | em | sup)*>

<!-- doc: Mesures du miroir (il est obligatoire de mentionner au minimum la hauteur et la largeur du miroir) -->
<!ELEMENT mesures (hauteur, largeur, profondeur?, poids?)>

<!-- doc: Hauteur du miroir en cm Exemples:
  200
  50 -->
<!ELEMENT hauteur (#PCDATA)>

<!-- doc: Largeur du miroir en cm Exemples:
  90
  150,5 -->
<!ELEMENT largeur (#PCDATA)>

<!-- doc: Profondeur du miroir en cm (à compléter si pertinent) Exemples:
  5
  0,25 -->
<!ELEMENT profondeur (#PCDATA)>

<!-- doc: Poids du miroir en kg (à compléter si pertinent) Exemples:
  52,9
  0,25 -->
<!ELEMENT poids (#PCDATA)>

<!-- doc: Informations sur l’origine du miroir. Il est obligatoire de préciser comment le collectionneur a obtenu le miroir. En fonction de cette réponse, d’autres informations pourront être renseignées comme le prix d’achat  -->
<!ELEMENT origine (commentaire?)>

<!-- doc: Date d’acquisition du miroir au format AAAA-MM-JJ. Élément obligatoire permettant d’attribuer les identifiants des miroirs (numérotation chronologique) Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST origine dateAcquisition NMTOKEN #REQUIRED>

<!-- doc: Contexte d'acquisition du miroir. Trois possibilités : achat, don ou indéterminé -->
<!ATTLIST origine moyenAcquisition (achat | don | indéterminé) #REQUIRED>

<!-- doc: Prix d'achat du miroir (à compléter si le miroir a été acheté et que cette information est connue) Exemples:
  50
  499 -->
<!ATTLIST origine prixAchatEuros CDATA #IMPLIED>

<!-- doc: Informations supplémentaires sur le miroir (par exemple sur son créateur ou sur le mouvement artistique dont il est issu). Texte libre qui peut comprendre plusieurs paragraphes, de l’emphase, des exposants et des liens, en fonction de la quantité d’informations que souhaite ajouter le collectionneur Exemples:
  Miroir très rare de fabrication italienne dont on ne trouve plus que dix exemplaires dans le monde
  <para> Ce miroir a été commercialisé en 2020 par l'enseigne <lienExterne URL="http://www.maisonsdumonde.com">Maison du monde</lienExterne></para> -->
<!ELEMENT commentaire (para+)>

<!-- doc: Valeur estimée du miroir (information facultative car évolutive et difficile à estimer) Exemples:
  100 €
  En février 2021, le prix du miroir était estimé à 715 € -->
<!ELEMENT valeur (#PCDATA)>

<!-- doc: Informations sur l’usage attendu du miroir. Texte libre qui peut comprendre plusieurs paragraphes, de l'emphase, des exposants et des liens, en fonction de la quantité d'informations que souhaite ajouter le collectionneur Exemples:
  Ce miroir de poche est très léger et peut se glisser facilement dans une valise
  Grand miroir d'entrée permettant de visualiser un corps en entier -->
<!ELEMENT usage (para+)>

<!-- doc: Bloc de paragraphe pouvant contenir des sous-éléments en emphase, en exposant et des liens (internes ou externes). Exemples:
  Un miroir très <em>british</em> !
  Dans le même style, voir également <lien ID="miroir22">ce miroir</lien>. -->
<!ELEMENT para (#PCDATA | em | sup | lienInterne | lienExterne)*>

<!-- doc: Passage en emphase. Exemples:
  style <em>british</em> et romantique
  miroir <em>so chic</em> -->
<!ELEMENT em (#PCDATA)>

<!-- doc: Passage en exposant. Exemples:
  XX<sup>e</sup> siècle
  sa 1<sup>re</sup> utilisation -->
<!ELEMENT sup (#PCDATA)>

<!-- doc: Lien pour renvoyer à un autre miroir de la collection dans un paragraphe de texte via son identifiant (attribut ID) Exemples:
  numéro 1
  ce miroir -->
<!ELEMENT lienInterne (#PCDATA)>

<!-- doc: Identifiant (ID) du miroir auquel le lien renvoie. Exemples:
  miroir1
  miroir22 -->
<!ATTLIST lienInterne ID NMTOKEN #REQUIRED>

<!-- doc: Lien pour renvoyer à une ressource externe via une URL Exemples:
  Bouclair
  Proantic.com -->
<!ELEMENT lienExterne (#PCDATA)>

<!-- doc: Ressource externe (URL) à laquelle le lien renvoie. Exemples:
  http://www.bouclair.com/fr/decor-mural/miroirs/
  http://www.proantic.com/miroir.php -->
<!ATTLIST lienExterne URL CDATA #REQUIRED>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir34.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir34" photo="oui">
    <suiviModif>
        <creation date="2021-03-01">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-03-02">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="transparent" forme="rond">
        <style epoque="contemporain">Ce miroir rond dit "Forest" a été conçu par la designer Sophie
            Larger. Il est à poser par le détenteur sur une base où se dressent des barres
            verticales en métal, avec finition en doré.</style>
        <cadre>Ces barres consituent un cadre décalé, dont le miroir semble glisser.</cadre>
    </aspect>
    <mesures>
        <hauteur>60</hauteur>
        <largeur>44</largeur>
        <profondeur>10</profondeur>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="1230">
        <dateAcquisition>2020-05-19</dateAcquisition>
        <commentaire>
            <para>Ce miroir circulaire, comme le <lienInterne ID="miroir50">miroir 50</lienInterne>,
                a été acheté chez Roche Bobois, l'un des leaders mondiaux du mobilier design haut de
                gamme. La fiche de ce produit est consultable sous ce <lienExterne
                    URL="https://www.roche-bobois.com/fr-CA/produit/forest-miroir"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 1230 dollars.</valeur>
    <usage>Ce miroir est voué à être fixé sur une commode, un buffet, un secrétaire.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir45.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/ownCloud/4_DESS/Trimestre2/INU3011_Docs-structures/EVAL/TP3/Modele/miroir.dtd">
<miroir ID="miroir45" photo="oui">
    <suiviModif>
        <creation date="2021-02-06">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-03-09">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="vert" forme="ovale">
        <style epoque="XXe siècle">Ce miroir moderne et coloré est créé et signé par l'artiste américain
            David Marshall. Conçu dans les années 1990, il est fait entièrement de verre sculpté. Un
            héron vert d'eau orne son pourtour. </style>
    </aspect>
    <mesures>
        <hauteur>99</hauteur>
        <largeur>71</largeur>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="XX€">
        <dateAcquisition>2019-09-17</dateAcquisition>
    </origine>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir34.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/Documents/GitHub/INU3011_TP/DTD/miroir.dtd">
<?xml-stylesheet type="text/xsl" href="file:/Users/Daphne/Documents/GitHub/INU3011_TP/XSLT/HTML.xsl"?>

<miroir ID="miroir34" photo="oui">
    <suiviModif>
        <création date="2021-02-27">
            <contributeur>Céline Hostiou</contributeur>
        </création>
    </suiviModif>
    <aspect couleur="transparent" forme="rond">
        <style époque="contemporain">
            <para>ce miroir rond dit « Forest » a été conçu par la designer Sophie
            Larger. Il est à poser par le détenteur sur une base où se dressent des barres
            verticales en métal, avec finition en doré.</para>
        </style>
        <cadre>
            <para>ces barres consituent un cadre décalé, dont le miroir semble glisser.</para>
        </cadre>
    </aspect>
    <mesures>
        <hauteur>60</hauteur>
        <largeur>44</largeur>
        <profondeur>10</profondeur>
    </mesures>
    <origine dateAcquisition="2018-09-19" moyenAcquisition="achat" prixAchatEuros="825">
        <commentaire>
            <para>Ce miroir circulaire, comme le <lienInterne ID="miroir50">miroir 50</lienInterne>,
                a été acheté chez Roche Bobois, l’un des leaders mondiaux du mobilier design haut de
                gamme. La fiche de ce produit est consultable sous ce <lienExterne
                    URL="https://www.roche-bobois.com/fr-CA/produit/forest-miroir"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 1230 $CAN (825 €).</valeur>
    <usage>
        <para>Ce miroir est voué à être fixé sur une commode, un buffet, un secrétaire.</para>
    </usage>
</miroir>
