=== DMathelier/INU3011_TP/DTD/miroir.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Modèle XML développé dans le cadre du cours INU3011 Documents structurés -->
<!-- EBSI - Université de Montréal -->

<!-- Équipe: Céline Hostiou (20096330), Daphné Mathelier (20177495). -->
<!-- Élément de plus haut niveau: miroir -->

<!--
Les commentaires commençant par "doc:" sont utilisés par oXygen comme documentation d’aide à la
saisie. Ils sont affichés en infobulles pendant l’édition de documents conformes à la DTD lorsque le
curseur survole un nom d’élément ou d’attribut.
-->

<!-- doc: Description d’un miroir -->
<!ELEMENT miroir (suiviModif, aspect, mesures, origine, valeur?, usage?) >

<!-- doc: Identifiant de la fiche qui correspond au numéro attribué au miroir (déterminé par la date d’acquisition). L’identifiant attribué à chaque miroir permet de nommer à la fois la fiche XML et l’image associée (s’il y en a une) Exemples:
  miroir1
  miroir22 -->
<!ATTLIST miroir ID NMTOKEN #REQUIRED>

<!-- doc: Attribut à n’utiliser que si une photo est associée à la fiche (indiquer "oui"). S’il n’y a pas de photo associée, ne pas utiliser cet attribut. -->
<!ATTLIST miroir photo (oui) #IMPLIED>

<!-- doc: Suivi des modifications apportées à la présente fiche -->
<!ELEMENT suiviModif (création, modification?)>

<!-- doc: Information sur la création de la fiche (obligatoire) -->
<!ELEMENT création (contributeur)>

<!-- doc: Date de création de la fiche au format AAA-MM-JJ Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST création date NMTOKEN #REQUIRED>

<!-- doc: Informations sur la dernière modification de la fiche -->
<!ELEMENT modification (contributeur)>

<!-- doc: Date de dernière modification de la fiche au format AAA-MM-JJ Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST modification date NMTOKEN #REQUIRED>

<!-- doc: Personne ayant créé ou modifié la fiche au format "Prénom Nom" (un seul contributeur par élément) Exemples:
  Daphné Mathelier
  Céline Hostiou -->
<!ELEMENT contributeur (#PCDATA)>

<!-- doc: Informations relatives à l’aspect du miroir. Il est obligatoire de renseigner la forme et la couleur du miroir selon des listes prédéfinies, ainsi que son style (au minimum son époque). D’autres renseignements sont facultatifs comme la présence d’un cadre ou l’orientation du miroir -->
<!ELEMENT aspect (style, cadre?)>

<!-- doc: Couleur principale du miroir. S’il y a plusieurs couleurs dominantes, choisir la valeur d’attribut "multicolore" -->
<!ATTLIST aspect couleur (argent | beige | blanc | bleu | brun | cuivre | gris | jaune | multicolore | noir | or | orange | rose | rouge | transparent | vert | violet) #REQUIRED>

<!-- doc: Forme du miroir. Si celle-ci est difficile à décrire, choisir la valeur d’attribut "irrégulier" -->
<!ATTLIST aspect forme (arabesque | carré | hexagone  | irrégulier  | octogone | ovale | rectangle | rond | triangle) #REQUIRED>

<!-- doc: Précisions sur le style si celui-ci est très marqué Exemples:
  Industriel
  Joli miroir <em>vintage</em> -->
<!ELEMENT style (#PCDATA | em | sup)*>

<!-- doc: Époque du miroir (précision obligatoire) Exemples:
  Contemporain
  XVIIIᵉ siècle -->
<!ATTLIST style époque CDATA #REQUIRED>

<!-- doc: Description du cadre (élément facultatif à n’utiliser que s’il y a un cadre à décrire) Exemples:
  Cadre en métal d’une épaisseur de 5 cm
  Discret cadre en faux bois -->
<!ELEMENT cadre (#PCDATA | em | sup)*>

<!-- doc: Mesures du miroir (il est obligatoire de mentionner au minimum la hauteur et la largeur du miroir) -->
<!ELEMENT mesures (hauteur, largeur, profondeur?, poids?)>

<!-- doc: Hauteur du miroir en cm Exemples:
  200
  50 -->
<!ELEMENT hauteur (#PCDATA)>

<!-- doc: Largeur du miroir en cm Exemples:
  90
  150,5 -->
<!ELEMENT largeur (#PCDATA)>

<!-- doc: Profondeur du miroir en cm (à compléter si pertinent) Exemples:
  5
  0,25 -->
<!ELEMENT profondeur (#PCDATA)>

<!-- doc: Poids du miroir en kg (à compléter si pertinent) Exemples:
  52,9
  0,25 -->
<!ELEMENT poids (#PCDATA)>

<!-- doc: Informations sur l’origine du miroir. Il est obligatoire de préciser comment le collectionneur a obtenu le miroir. En fonction de cette réponse, d’autres informations pourront être renseignées comme le prix d’achat  -->
<!ELEMENT origine (commentaire?)>

<!-- doc: Date d’acquisition du miroir au format AAAA-MM-JJ. Élément obligatoire permettant d’attribuer les identifiants des miroirs (numérotation chronologique) Exemples:
  2021-03-08
  1989-10-09 -->
<!ATTLIST origine dateAcquisition NMTOKEN #REQUIRED>

<!-- doc: Contexte d'acquisition du miroir. Trois possibilités : achat, don ou indéterminé -->
<!ATTLIST origine moyenAcquisition (achat | don | indéterminé) #REQUIRED>

<!-- doc: Prix d'achat du miroir (à compléter si le miroir a été acheté et que cette information est connue) Exemples:
  50
  499 -->
<!ATTLIST origine prixAchatEuros CDATA #IMPLIED>

<!-- doc: Informations supplémentaires sur le miroir (par exemple sur son créateur ou sur le mouvement artistique dont il est issu). Texte libre qui peut comprendre plusieurs paragraphes, de l’emphase, des exposants et des liens, en fonction de la quantité d’informations que souhaite ajouter le collectionneur Exemples:
  Miroir très rare de fabrication italienne dont on ne trouve plus que dix exemplaires dans le monde
  <para> Ce miroir a été commercialisé en 2020 par l'enseigne <lienExterne URL="http://www.maisonsdumonde.com">Maison du monde</lienExterne></para> -->
<!ELEMENT commentaire (para+)>

<!-- doc: Valeur estimée du miroir (information facultative car évolutive et difficile à estimer) Exemples:
  100 €
  En février 2021, le prix du miroir était estimé à 715 € -->
<!ELEMENT valeur (#PCDATA)>

<!-- doc: Informations sur l’usage attendu du miroir. Texte libre qui peut comprendre plusieurs paragraphes, de l'emphase, des exposants et des liens, en fonction de la quantité d'informations que souhaite ajouter le collectionneur Exemples:
  Ce miroir de poche est très léger et peut se glisser facilement dans une valise
  Grand miroir d'entrée permettant de visualiser un corps en entier -->
<!ELEMENT usage (para+)>

<!-- doc: Bloc de paragraphe pouvant contenir des sous-éléments en emphase, en exposant et des liens (internes ou externes). Exemples:
  Un miroir très <em>british</em> !
  Dans le même style, voir également <lien ID="miroir22">ce miroir</lien>. -->
<!ELEMENT para (#PCDATA | em | sup | lienInterne | lienExterne)*>

<!-- doc: Passage en emphase. Exemples:
  style <em>british</em> et romantique
  miroir <em>so chic</em> -->
<!ELEMENT em (#PCDATA)>

<!-- doc: Passage en exposant. Exemples:
  XX<sup>e</sup> siècle
  sa 1<sup>re</sup> utilisation -->
<!ELEMENT sup (#PCDATA)>

<!-- doc: Lien pour renvoyer à un autre miroir de la collection dans un paragraphe de texte via son identifiant (attribut ID) Exemples:
  numéro 1
  ce miroir -->
<!ELEMENT lienInterne (#PCDATA)>

<!-- doc: Identifiant (ID) du miroir auquel le lien renvoie. Exemples:
  miroir1
  miroir22 -->
<!ATTLIST lienInterne ID NMTOKEN #REQUIRED>

<!-- doc: Lien pour renvoyer à une ressource externe via une URL Exemples:
  Bouclair
  Proantic.com -->
<!ELEMENT lienExterne (#PCDATA)>

<!-- doc: Ressource externe (URL) à laquelle le lien renvoie. Exemples:
  http://www.bouclair.com/fr/decor-mural/miroirs/
  http://www.proantic.com/miroir.php -->
<!ATTLIST lienExterne URL CDATA #REQUIRED>

=== DMathelier/INU3011_TP/XML/miroir12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/Documents/GitHub/INU3011_TP/DTD/miroir.dtd">
<?xml-stylesheet type="text/xsl" href="file:/Users/Daphne/Documents/GitHub/INU3011_TP/XSLT/HTML.xsl"?>

<miroir ID="miroir12" photo="oui">
    <suiviModif>
        <création date="2021-01-22">
            <contributeur>Céline Hostiou</contributeur>
        </création>
    </suiviModif>
    <aspect couleur="or" forme="octogone">
        <style époque="vintage">
            <para>ce miroir dit « Makita », de la marque AMPM, est décoré de deux carrés en laiton superposés.</para>
        </style>
        <cadre>
            <para>le cadre en métal a fait l’objet d'une finition en laiton vieilli.</para></cadre>
    </aspect>
    <mesures>
        <hauteur>70</hauteur>
        <largeur>70</largeur>
    </mesures>
    <origine dateAcquisition="2017-02-13" moyenAcquisition="don">
        <commentaire>
            <para>Ce miroir vintage, comme le <lienInterne ID="miroir22">miroir
                22</lienInterne>, est proposé par les Galeries Lafayette. Sa fiche produit se trouve sous ce <lienExterne
                    URL="https://www.galerieslafayette.com/p/miroir+metal+finition+vieillie+makita-ampm/300407151727/347"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 259 €.</valeur>
    <usage>
        <para>Ce miroir peut être indifféremment posé sur une commode, un meuble ou fixé au mur.</para>
    </usage>
</miroir>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir26" photo="oui">
    <suiviModif>
        <creation date="2021-02-20">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-02-21">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="noir" forme="triangle">
        <style epoque="contemporain">Ce miroir triangulaire de marque "Tikamoon" et de modèle "Maho"
            est rehaussé de quatre barres superposées, ouvragées. Celles-ci épousent l'angle supérieur du triangle.</style>
        <cadre>Le cadre, en métal peint, apporte une touche industrielle et graphique à la pièce où
            il est exposé.</cadre>
    </aspect>
    <mesures>
        <hauteur>60</hauteur>
        <largeur>60</largeur>
        <profondeur>4</profondeur>
        <poids>8</poids>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="149">
        <dateAcquisition>2020-05-01</dateAcquisition>
        <commentaire>
            <para>Ce miroir triangulaire, comme le <lienInterne ID="miroir38">miroir
                    38</lienInterne>, a été conçu par l'entreprise Tikamoon, située dans le nord de
                la France, à Lille. Celle-ci s'inscrit dans un créneau de meubles durables. Elle a
                développé une chaîne de production à l'impact environnemental limité. La fiche produit du miroir est consultable sous ce 
                    <lienExterne
                        URL="https://www.tikamoon.com/art-miroir-triangulaire-en-m-tal-60-maho-2782.htm"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 149 euros.</valeur>
    <usage>Ce miroir peut agrémenté toutes les pièces de la maison.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir22.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/Documents/GitHub/INU3011_TP/DTD/miroir.dtd">
<?xml-stylesheet type="text/xsl" href="file:/Users/Daphne/Documents/GitHub/INU3011_TP/XSLT/HTML.xsl"?>

<miroir ID="miroir22" photo="oui">
    <suiviModif>
        <création date="2021-02-03">
            <contributeur>Céline Hostiou</contributeur>
        </création>
    </suiviModif>
    <aspect couleur="argent" forme="rond">
        <style époque="vintage">
            <para>Ce miroir rond date des années 1960. Il a pour matériaux le verre et
            le cristal.</para>
        </style>
        <cadre>
            <para>Le cadre est gravé et biseauté.</para>
        </cadre>
    </aspect>
    <mesures>
        <hauteur>62</hauteur>
        <largeur>62</largeur>
    </mesures>
    <origine dateAcquisition="2017-12-15" moyenAcquisition="achat" prixAchatEuros="250">
        <commentaire>
            <para>Ce miroir circulaire, comme le <lienInterne ID="miroir50">miroir 50</lienInterne>,
                a été acquis auprès d'un brocanteur de Saint-Ouen, situé près de Paris. Bien que
                d'occasion, il ne présente ni fêlés ni impacts. Il est visible sous ce <lienExterne
                    URL="https://www.selency.fr/produit/55V2Q3Y2/miroir-rond-grave-et-biseaute-annees-60.html"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 250 euros.</valeur>
    <usage>
        <para>Ce miroir peut être fixé dans n'importe quelle pièce du logement, dans un vestibule, un
            couloir.</para>
    </usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/Documents/GitHub/INU3011_TP/DTD/miroir.dtd">
<?xml-stylesheet type="text/xsl" href="file:/Users/Daphne/Documents/GitHub/INU3011_TP/XSLT/HTML.xsl"?>

<miroir ID="miroir26" photo="oui">
    <suiviModif>
        <création date="2021-02-12">
            <contributeur>Céline Hostiou</contributeur>
        </création>
        <modification date="2021-03-01">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="noir" forme="triangle">
        <style époque="contemporain">
            <para>Ce miroir triangulaire de marque "Tikamoon" et de modèle "Maho"
                est rehaussé de quatre barres superposées, ouvragées. Celles-ci épousent l'angle supérieur du triangle.</para>
        </style>
        <cadre>
            <para>Le cadre, en métal peint, apporte une touche industrielle et graphique à la pièce où il est exposé.</para>
        </cadre>
    </aspect>
    <mesures>
        <hauteur>60</hauteur>
        <largeur>60</largeur>
        <profondeur>4</profondeur>
        <poids>8</poids>
    </mesures>
    <origine dateAcquisition="2018-02-01" moyenAcquisition="achat" prixAchatEuros="149">
        <commentaire>
            <para>Ce miroir triangulaire, comme le <lienInterne ID="miroir38">miroir
                    38</lienInterne>, a été conçu par l'entreprise Tikamoon, située dans le nord de
                la France, à Lille. Celle-ci s'inscrit dans un créneau de meubles durables. Elle a
                développé une chaîne de production à l'impact environnemental limité. La fiche produit du miroir est consultable sous ce 
                    <lienExterne
                        URL="https://www.tikamoon.com/art-miroir-triangulaire-en-m-tal-60-maho-2782.htm"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 149 euros.</valeur>
    <usage>
        <para>Ce miroir peut agrémenté toutes les pièces de la maison.</para>
    </usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir50.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/ownCloud/4_DESS/Trimestre2/INU3011_Docs-structures/EVAL/TP3/Modele/miroir.dtd">
<miroir ID="miroir50" photo="oui">
    <suiviModif>
        <creation date="2021-02-12">
            <contributeur>Daphné Mathelier</contributeur>
        </creation>
        <modification date="2021-03-09">
            <contributeur>Céline Hostiou</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="or" forme="rond">
        <style epoque="contemporain">Ce miroir est composé d'une structure à double cercles en métal
            doré, d'un verre miroir à biseaux et comporte un dessin d'étoile.</style>
        <cadre>Le miroir est entouré d'un cadre doré très fin.</cadre>
    </aspect>
    <mesures>
        <hauteur>120</hauteur>
        <largeur>120</largeur>
        <profondeur>4</profondeur>
        <poids>10</poids>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="1196,90 €">
        <dateAcquisition>2021-02-10</dateAcquisition>
        <commentaire>
            <para>Ce miroir fait partie de la collection 2021 de l'enseigne Maisons du monde. Il
                permet selon le vendeur de donner un <em>coup d'éclat</em> à son intérieur (voir la
                description complète sur le <lienExterne
                    URL="http://www.maisonsdumonde.com/FR/fr/p/miroir-rond-or-etoile-d120-M20020841.htm"
                    >site</lienExterne> de Maisons du monde).</para>
            <para>Dans le même style, voir le <lienInterne ID="miroir22">miroir 22</lienInterne> de la collection.</para>
        </commentaire>
    </origine>
    <valeur>En mars 2020 le prix du miroir était à 1196,90 €</valeur>
    <usage>Ce miroir à fixer peut trouver sa place dans toutes les pièces de la maison.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/Daphne/Documents/GitHub/INU3011_TP/DTD/miroir.dtd">
<?xml-stylesheet type="text/xsl" href="file:/Users/Daphne/Documents/GitHub/INU3011_TP/XSLT/HTML.xsl"?>

<miroir ID="miroir17" photo="oui">
    <suiviModif>
        <création date="2021-01-28">
            <contributeur>Céline Hostiou</contributeur>
        </création>
        <modification date="2021-03-01">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="or" forme="rond">
        <style époque="contemporain">
            <para>ce miroir appelé « Capsule » se décompose en deux parties : un petit cercle
            surmontant un plus grand. Ceux-ci sont unis par une fine tige ovoïde.</para>
        </style>
        <cadre>
            <para>le cadre est en métal doré.</para>
        </cadre>
    </aspect>
    <mesures>
        <hauteur>66</hauteur>
        <largeur>41</largeur>
    </mesures>
    <origine dateAcquisition="2017-04-01" moyenAcquisition="achat" prixAchatEuros="62">
        <commentaire>
            <para>Ce miroir circulaire, comme le <lienInterne ID="miroir22">miroir
                22</lienInterne>, a été acheté dans l’enseigne de décoration québécoise Zone. Il est
                visible sous ce <lienExterne
                    URL="https://www.zonemaison.com/fr/products/deco/miroirs/capsule/23754/miroir-double-or"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 92 $CAN (62 €).</valeur>
    <usage>
        <para>Ce miroir aurait avantage à être placé dans une pièce lumineuse, pour l’éclat de son cadre doré.</para>
    </usage>
</miroir>

=== DMathelier/INU3011_TP/XML/Fiches-Celine/miroir29.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir29" photo="oui">
    <suiviModif>
        <creation date="2021-02-27">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-02-28">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="noir" forme="rectangle">
        <style epoque="contemporain">Ce miroir rectangulaire dit "Karmsund", vendu par la chaîne de
            magasins Ikea, se déploie en triptyque. Il dispose de pieds et est coiffé d'une
            ornementation, tous en fer forgé, tous détachables.</style>
        <cadre>Le cadre est en acier galvanisé noir.</cadre>
    </aspect>
    <mesures>
        <hauteur>80</hauteur>
        <largeur>74</largeur>
        <profondeur>6</profondeur>
        <poids>7,10</poids>
    </mesures>
    <origine moyenAcquisition="achat" prixAchat="49,99">
        <dateAcquisition>2020-05-12</dateAcquisition>
        <commentaire>
            <para>Ce miroir rectangulaire, comme le <lienInterne ID="miroir42">miroir
                    42</lienInterne>, a été acheté chez Ikea. La fiche de ce produit est consultable
                sous ce <lienExterne
                    URL="https://www.ikea.com/ca/fr/p/karmsund-miroir-de-table-noir-20294983/"
                    >lien</lienExterne>.</para>
        </commentaire>
    </origine>
    <valeur>En mai 2020, le prix du miroir était de 49,99 dollars.</valeur>
    <usage>Des crochets situés derrière les miroirs latéraux permettent de ranger facilement ses
        bijoux. Les sections pivotantes du miroir permettent de s'admirer sous différents angles.
        Peut être installé dans toutes les pièces de la maison, dont la salle de bains, car il a été
        testé et approuvé pour cet usage.</usage>
</miroir>

=== DMathelier/INU3011_TP/XML/miroir5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE miroir SYSTEM "file:/Users/celinehostiou/Dropbox/Mon%20Mac%20(MacBook%20Air%20de%20C%C3%A9line)/Documents/DESS%20%C3%A9dition%20num%C3%A9rique%20UdeM/Hiver_2021/-%20INU3011_Documents_structur%C3%A9s/-%20%C3%89valuations/-%20TP3_Mod%C3%A9lisation_pr%C3%A9liminaire/Modele/miroir.dtd">
<miroir ID="miroir5" photo="non">
    <suiviModif>
        <creation date="2021-02-06">
            <contributeur>Céline Hostiou</contributeur>
        </creation>
        <modification date="2021-03-09">
            <contributeur>Daphné Mathelier</contributeur>
        </modification>
    </suiviModif>
    <aspect couleur="transparent" forme="octogone">
        <style epoque="XXe siècle">Ce miroir octogonal comporte dans sa partie inférieure un vase
            capable de contenir des fleurs artificielles. Des fragments de miroir en bandes
            verticales se trouvent sur ses parties latérales et donnent un effet d'éclatement de la
            perspective.</style>
    </aspect>
    <mesures>
        <hauteur>24</hauteur>
        <largeur>24</largeur>
    </mesures>
    <origine moyenAcquisition="don">
        <dateAcquisition>2017-02-13</dateAcquisition>
    </origine>
</miroir>
